name: CI

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libgbm-dev libatk-bridge2.0-0 libgtk-3-0 libx11-xcb1 libnss3 libxss1

      - name: Install dependencies
        run: |
          npm ci
          npm install web-streams-polyfill
          npx playwright install --with-deps
          npx playwright install-deps

      - name: Set environment variables
        run: |
          echo "HEADLESS=true" >> $GITHUB_ENV
          echo "NODE_OPTIONS=--experimental-vm-modules --max_old_space_size=4096 -r web-streams-polyfill/ponyfill/es6" >> $GITHUB_ENV

      - name: Run Playwright tests
        run: |
          node --version
          npx playwright test --reporter=line,allure-playwright
        env:
          NODE_OPTIONS: >-
            --experimental-vm-modules 
            --max_old_space_size=4096 
            -r web-streams-polyfill/ponyfill/es6

      - name: Generate Allure report
        if: always()
        run: |
          npx allure generate allure-results --clean -o allure-report
          zip -r allure-report.zip allure-report

      - name: Upload Allure report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: allure-report.zip

      - name: Upload Playwright test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-test-results
          path: test-results/
          retention-days: 7

      - name: Output debug information on failure
        if: failure()
        run: |
          echo "Node.js version:"
          node --version
          echo "NPM version:"
          npm --version
          echo "Installed browsers:"
          npx playwright show-browsers
          cat /home/runner/.npm/_logs/*-debug.log